"""Remove unique constraint on password_hash, widen to 255

Revision ID: 19296fedeb95
Revises: c00fc9ba4ba2
Create Date: 2026-06-24 11:10:25.382664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19296fedeb95'
down_revision = 'c00fc9ba4ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('users_password_hash_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_password_hash_key', ['password_hash'])
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
